version: 2
updates:
  - package-ecosystem: docker
    directory: /alpine-redis-amd64/
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /alpine-redis-armhf/
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /alpine-redis-aarch64/
    schedule:
      interval: weekly